version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend
    volumes:
      - ./backend:/usr/src
      - ./backend/nodemon.json:/usr/src/nodemon.json
      - /usr/src/node_modules
    env_file:
      - .env.dev
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - START_MONGODB=${START_MONGODB}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - END_MONGODB=${END_MONGODB}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - FRONT_END=http://localhost
      - BACK_END="http://frontend"
      - PRODUCTION=false
    command: npm run dev
    networks:
      - tapebin
  frontend:
    container_name: frontend
    depends_on:
      - backend
    restart: always
    ports:
    - 3000:3000
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src
      - /usr/src/.next
      - /usr/src/node_modules
    environment:
      BACK_END: "http://backend"
    networks:
      - tapebin
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
    - ./nginx/ssl:/etc/ssl
    restart: always
    networks:
      - tapebin
networks:
  tapebin:
    driver: bridge
