version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.dev
    container_name: backend
    networks:
      - tapebin-network
    expose:
      - "5001"
    ports:
      - "5001:5001"
    volumes:
      - ./backend:/usr/src
      - ./backend/nodemon.json:/usr/src/nodemon.json
      - /usr/src/node_modules
    env_file:
      - .env.dev
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - START_MONGODB=${START_MONGODB}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - END_MONGODB=${END_MONGODB}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - FRONT_END=http://localhost:3000
      - BACK_END=http://localhost:5001
      - PRODUCTION=false
    command: npm run dev
  frontend:
    container_name: frontend
    networks:
      - tapebin-network
    depends_on:
      - backend
    expose:
      - "3000"
    ports:
      - "3000:3000"
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/usr/src
      - /usr/src/.next
      - /usr/src/node_modules
    environment:
      BACK_END: http://localhost:5001
networks:
  tapebin-network:
    driver: bridge
