version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    expose:
      - "5000"
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src
      - ./backend/nodemon.json:/usr/src/nodemon.json
    environment:
      - SESSION_SECRET="${SESSION_SECRET}"
      - START_MONGO="${START_MONGO}"
      - MONGODB_USERNAME="${MONGODB_USERNAME}"
      - MONGODB_PASSWORD="${MONGODB_PASSWORD}"
      - END_MONGODB="${END_MONGODB}"
      - GITHUB_CLIENT_ID="${GITHUB_CLIENT_ID}"
      - GITHUB_CLIENT_SECRET="${GITHUB_CLIENT_SECRET}"
    command: node build/index.js
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src
      - /usr/src/.next
      - /usr/src/node_modules
    environment:
      - BACK_END=http://backend:5000
