version: "3"
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
      - START_MONGODB=${START_MONGODB}
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - END_MONGODB=${END_MONGODB}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - FRONT_END=http://localhost
      - BACK_END="http://frontend"
      - PRODUCTION=true
    command: node build/index.js
    networks:
      - tapebin
  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACK_END=http://backend:5000
    depends_on:
      - backend
    networks:
      - tapebin
  nginx:
    container_name: nginx
    build:
      context: nginx
      dockerfile: Dockerfile
    depends_on:
      - frontend
      - backend
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/ssl:/etc/ssl
    restart: always
    networks:
      - tapebin
networks:
  tapebin:
    driver: bridge
